_wandb:
    value:
        cli_version: 0.22.3
        e:
            s2uk55j9hzjo1putt1q1far6o2grqb7k:
                codePath: vqvae_train/mini_runnable.py
                codePathLocal: mini_runnable.py
                email: haochen235@g.ucla.edu
                executable: /opt/anaconda3/envs/ColOCR_env/bin/python
                git:
                    commit: 6de1da54ec322038dbcf4ccd0a5fc1602a2b0d1d
                    remote: git@github.com:HaochenZhang717/TimeSeriesAnomaly.git
                host: Haochens-MacBook-Pro.local
                os: macOS-14.3-arm64-arm-64bit
                program: /Users/zhc/Documents/PhD/projects/TimeSeriesAnomaly/code/vqvae_train/mini_runnable.py
                python: CPython 3.12.0
                root: /Users/zhc/Documents/PhD/projects/TimeSeriesAnomaly/code/vqvae_train
                startedAt: "2025-12-17T09:41:25.216300Z"
                writerId: s2uk55j9hzjo1putt1q1far6o2grqb7k
        m: []
        python_version: 3.12.0
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 13
                - 16
            "4": 3.12.0
            "5": 0.22.3
            "12": 0.22.3
            "13": darwin-arm64
batch_size:
    value: 64
beta:
    value: 0.25
code_dim:
    value: 8
device:
    value: cpu
epochs:
    value: 50
hidden:
    value: 64
indices_path:
    value: ../dataset_utils/ECG_datasets/indices/slide_windows_106npz/train/normal.jsonl
lr:
    value: 0.001
num_codes:
    value: 20
one_channel:
    value: true
raw_data_path:
    value: ../dataset_utils/ECG_datasets/raw_data/106.npz
recon_loss:
    value: mse
save_path:
    value: vqvae_1d.pt
vq_loss_weight:
    value: 1
weight_decay:
    value: 0.01
